FROM python:3.11-slim

WORKDIR /app
COPY server/gateway/fastapi /app

# lighter deps
RUN pip install --no-cache-dir fastapi uvicorn pydantic-settings

EXPOSE 8080
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080"]
