version: "3.9"
services:
  gateway:
    build:
      context: ../..
      dockerfile: server/docker/Dockerfile.gateway
    ports:
      - "8080:8080"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
    restart: unless-stopped
